-- ============================================
-- Схема базы данных для системы изучения общественного мнения
-- Соответствует утверждённой ER-модели
-- БКНФ: все таблицы нормализованы, нет избыточных зависимостей
-- ============================================

-- Справочник полов
CREATE TABLE POL (
    ID_POLA INTEGER NOT NULL,
    NAIMENOVANIE VARCHAR(50) NOT NULL,
    CONSTRAINT POL_PK PRIMARY KEY (ID_POLA),
    CONSTRAINT POL_NAIMENOVANIE_UNIQUE UNIQUE (NAIMENOVANIE)
);

COMMENT ON TABLE POL IS 'Справочник полов';

-- Справочник регионов
CREATE TABLE REGION (
    ID_REGIONA INTEGER NOT NULL,
    NAIMENOVANIE VARCHAR(100) NOT NULL,
    CONSTRAINT REGION_PK PRIMARY KEY (ID_REGIONA),
    CONSTRAINT REGION_NAIMENOVANIE_UNIQUE UNIQUE (NAIMENOVANIE)
);

COMMENT ON TABLE REGION IS 'Справочник регионов';

-- Справочник уровней образования
CREATE TABLE UROVEN_OBRAZOVANIYA (
    ID_UROVNYA INTEGER NOT NULL,
    NAIMENOVANIE VARCHAR(100) NOT NULL,
    CONSTRAINT UROVEN_OBRAZOVANIYA_PK PRIMARY KEY (ID_UROVNYA),
    CONSTRAINT UROVEN_OBRAZOVANIYA_NAIMENOVANIE_UNIQUE UNIQUE (NAIMENOVANIE)
);

COMMENT ON TABLE UROVEN_OBRAZOVANIYA IS 'Справочник уровней образования';

-- Таблица опросов
-- Обоснование БКНФ: все атрибуты зависят только от PK (ID_OPROSA)
CREATE TABLE OPROS (
    ID_OPROSA INTEGER NOT NULL,
    TEMA VARCHAR(255) NOT NULL,
    OPISANIE TEXT,
    DATA_NACHALA DATE NOT NULL,
    DATA_OKONCH_PLN DATE NOT NULL,
    DATA_OKONCH_FAKT DATE,
    MIN_KOL_OTVETOV INTEGER NOT NULL CHECK (MIN_KOL_OTVETOV > 0),
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('draft', 'active', 'closed')),
    CONSTRAINT OPROS_PK PRIMARY KEY (ID_OPROSA),
    CONSTRAINT OPROS_DATES_CHECK CHECK (DATA_NACHALA <= DATA_OKONCH_PLN)
);

COMMENT ON TABLE OPROS IS 'Опросы. Статусы: draft - черновик, active - активен, closed - закрыт';
COMMENT ON COLUMN OPROS.DATA_OKONCH_FAKT IS 'Фактическая дата окончания (может отличаться от плановой при продлении)';
COMMENT ON COLUMN OPROS.MIN_KOL_OTVETOV IS 'Минимальное количество участников для успешного завершения опроса';

-- Таблица вопросов
-- Обоснование БКНФ: все атрибуты зависят только от PK (ID_VOPROSA), ID_OPROSA - FK
CREATE TABLE VOPROS (
    ID_VOPROSA INTEGER NOT NULL,
    ID_OPROSA INTEGER NOT NULL,
    TEKST_VOPROSA TEXT NOT NULL,
    PORYADOK INTEGER NOT NULL,
    TIP_VOPROSA VARCHAR(20) NOT NULL DEFAULT 'single_choice' CHECK (TIP_VOPROSA = 'single_choice'),
    CONSTRAINT VOPROS_PK PRIMARY KEY (ID_VOPROSA),
    CONSTRAINT VOPROS_OPROS_FK FOREIGN KEY (ID_OPROSA) REFERENCES OPROS(ID_OPROSA) ON DELETE CASCADE,
    CONSTRAINT VOPROS_OPROS_PORYADOK_UNIQUE UNIQUE (ID_OPROSA, PORYADOK)
);

COMMENT ON TABLE VOPROS IS 'Вопросы в опросах. Порядок определяется PORYADOK';

-- Таблица вариантов ответов
-- Обоснование БКНФ: все атрибуты зависят только от PK (ID_VARIANTA), ID_VOPROSA - FK
CREATE TABLE VARIANT_OTVETA (
    ID_VARIANTA INTEGER NOT NULL,
    ID_VOPROSA INTEGER NOT NULL,
    TEKST_VARIANTA VARCHAR(255) NOT NULL,
    PORYADOK INTEGER NOT NULL,
    PRIZNAK_POLOZH INTEGER NOT NULL DEFAULT 0 CHECK (PRIZNAK_POLOZH IN (0, 1)),
    CONSTRAINT VARIANT_OTVETA_PK PRIMARY KEY (ID_VARIANTA),
    CONSTRAINT VARIANT_OTVETA_VOPROS_FK FOREIGN KEY (ID_VOPROSA) REFERENCES VOPROS(ID_VOPROSA) ON DELETE CASCADE,
    CONSTRAINT VARIANT_OTVETA_VOPROS_PORYADOK_UNIQUE UNIQUE (ID_VOPROSA, PORYADOK)
);

COMMENT ON TABLE VARIANT_OTVETA IS 'Варианты ответов на вопросы. PRIZNAK_POLOZH = 1 если ответ считается положительным';
COMMENT ON COLUMN VARIANT_OTVETA.PRIZNAK_POLOZH IS '1 - положительный ответ, 0 - отрицательный (для анализа динамики)';

-- Таблица респондентов
-- Обоснование БКНФ: все атрибуты зависят только от PK (ID_RESPONDENTA)
-- ФИО хранится отдельными полями, но НИКОГДА не выводится в отчётах (анонимность)
CREATE TABLE RESPONDENT (
    ID_RESPONDENTA INTEGER NOT NULL,
    FAMILIYA VARCHAR(100),
    IMYA VARCHAR(100),
    OTCHESTVO VARCHAR(100),
    DATA_ROZHDENIYA DATE NOT NULL,
    ID_POLA INTEGER NOT NULL,
    ID_REGIONA INTEGER NOT NULL,
    ID_UROVNYA INTEGER NOT NULL,
    CONSTRAINT RESPONDENT_PK PRIMARY KEY (ID_RESPONDENTA),
    CONSTRAINT RESPONDENT_POL_FK FOREIGN KEY (ID_POLA) REFERENCES POL(ID_POLA),
    CONSTRAINT RESPONDENT_REGION_FK FOREIGN KEY (ID_REGIONA) REFERENCES REGION(ID_REGIONA),
    CONSTRAINT RESPONDENT_UROVEN_FK FOREIGN KEY (ID_UROVNYA) REFERENCES UROVEN_OBRAZOVANIYA(ID_UROVNYA)
);

COMMENT ON TABLE RESPONDENT IS 'Респонденты. ФИО хранится, но НИКОГДА не выводится в отчётах (анонимность)';
COMMENT ON COLUMN RESPONDENT.FAMILIYA IS 'Фамилия (не используется в отчётах)';
COMMENT ON COLUMN RESPONDENT.IMYA IS 'Имя (не используется в отчётах)';
COMMENT ON COLUMN RESPONDENT.OTCHESTVO IS 'Отчество (не используется в отчётах)';

-- Таблица участия респондентов в опросах
-- Обоснование БКНФ: фиксирует факт участия респондента в опросе
-- Уникальность: один респондент может участвовать в одном опросе только один раз
CREATE TABLE UCHASTIE (
    ID_UCHASTIYA INTEGER NOT NULL,
    ID_OPROSA INTEGER NOT NULL,
    ID_RESPONDENTA INTEGER NOT NULL,
    DATA_UCHASTIYA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UCHASTIE_PK PRIMARY KEY (ID_UCHASTIYA),
    CONSTRAINT UCHASTIE_OPROS_FK FOREIGN KEY (ID_OPROSA) REFERENCES OPROS(ID_OPROSA) ON DELETE CASCADE,
    CONSTRAINT UCHASTIE_RESPONDENT_FK FOREIGN KEY (ID_RESPONDENTA) REFERENCES RESPONDENT(ID_RESPONDENTA) ON DELETE CASCADE,
    CONSTRAINT UCHASTIE_OPROS_RESPONDENT_UNIQUE UNIQUE (ID_OPROSA, ID_RESPONDENTA)
);

COMMENT ON TABLE UCHASTIE IS 'Участие респондентов в опросах. Один респондент может участвовать в одном опросе только один раз';

-- Таблица ответов респондентов
-- Обоснование БКНФ: все атрибуты зависят только от PK (ID_OTVETA)
-- Уникальность: один респондент может ответить на вопрос опроса только один раз
CREATE TABLE OTVET (
    ID_OTVETA INTEGER NOT NULL,
    ID_OPROSA INTEGER NOT NULL,
    ID_VOPROSA INTEGER NOT NULL,
    ID_RESPONDENTA INTEGER NOT NULL,
    ID_VARIANTA INTEGER NOT NULL,
    DATA_OTVETA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT OTVET_PK PRIMARY KEY (ID_OTVETA),
    CONSTRAINT OTVET_OPROS_FK FOREIGN KEY (ID_OPROSA) REFERENCES OPROS(ID_OPROSA) ON DELETE CASCADE,
    CONSTRAINT OTVET_VOPROS_FK FOREIGN KEY (ID_VOPROSA) REFERENCES VOPROS(ID_VOPROSA) ON DELETE CASCADE,
    CONSTRAINT OTVET_RESPONDENT_FK FOREIGN KEY (ID_RESPONDENTA) REFERENCES RESPONDENT(ID_RESPONDENTA) ON DELETE CASCADE,
    CONSTRAINT OTVET_VARIANT_FK FOREIGN KEY (ID_VARIANTA) REFERENCES VARIANT_OTVETA(ID_VARIANTA) ON DELETE CASCADE,
    CONSTRAINT OTVET_OPROS_VOPROS_RESPONDENT_UNIQUE UNIQUE (ID_OPROSA, ID_VOPROSA, ID_RESPONDENTA)
);

COMMENT ON TABLE OTVET IS 'Ответы респондентов на вопросы опросов. Один респондент может ответить на вопрос опроса только один раз';
COMMENT ON COLUMN OTVET.DATA_OTVETA IS 'Время ответа (для анализа динамики)';

-- Индексы для оптимизации запросов
CREATE INDEX IDX_VOPROS_OPROS_ID ON VOPROS(ID_OPROSA);
CREATE INDEX IDX_VARIANT_OTVETA_VOPROS_ID ON VARIANT_OTVETA(ID_VOPROSA);
CREATE INDEX IDX_UCHASTIE_OPROS_ID ON UCHASTIE(ID_OPROSA);
CREATE INDEX IDX_UCHASTIE_RESPONDENT_ID ON UCHASTIE(ID_RESPONDENTA);
CREATE INDEX IDX_UCHASTIE_DATA ON UCHASTIE(DATA_UCHASTIYA);
CREATE INDEX IDX_OTVET_OPROS_ID ON OTVET(ID_OPROSA);
CREATE INDEX IDX_OTVET_VOPROS_ID ON OTVET(ID_VOPROSA);
CREATE INDEX IDX_OTVET_RESPONDENT_ID ON OTVET(ID_RESPONDENTA);
CREATE INDEX IDX_OTVET_DATA ON OTVET(DATA_OTVETA);
CREATE INDEX IDX_RESPONDENT_DATA_ROZHDENIYA ON RESPONDENT(DATA_ROZHDENIYA);
CREATE INDEX IDX_RESPONDENT_POL ON RESPONDENT(ID_POLA);
CREATE INDEX IDX_RESPONDENT_REGION ON RESPONDENT(ID_REGIONA);
CREATE INDEX IDX_RESPONDENT_UROVEN ON RESPONDENT(ID_UROVNYA);
