-- ============================================
-- Sequences для генерации первичных ключей
-- Используем явные sequences вместо SERIAL/IDENTITY
-- ============================================

CREATE SEQUENCE POL_ID_POLA_SEQ;
CREATE SEQUENCE REGION_ID_REGIONA_SEQ;
CREATE SEQUENCE UROVEN_OBRAZOVANIYA_ID_UROVNYA_SEQ;
CREATE SEQUENCE OPROS_ID_OPROSA_SEQ;
CREATE SEQUENCE VOPROS_ID_VOPROSA_SEQ;
CREATE SEQUENCE VARIANT_OTVETA_ID_VARIANTA_SEQ;
CREATE SEQUENCE RESPONDENT_ID_RESPONDENTA_SEQ;
CREATE SEQUENCE UCHASTIE_ID_UCHASTIYA_SEQ;
CREATE SEQUENCE OTVET_ID_OTVETA_SEQ;

-- Установка значений по умолчанию для PK
ALTER TABLE POL ALTER COLUMN ID_POLA SET DEFAULT nextval('POL_ID_POLA_SEQ');
ALTER TABLE REGION ALTER COLUMN ID_REGIONA SET DEFAULT nextval('REGION_ID_REGIONA_SEQ');
ALTER TABLE UROVEN_OBRAZOVANIYA ALTER COLUMN ID_UROVNYA SET DEFAULT nextval('UROVEN_OBRAZOVANIYA_ID_UROVNYA_SEQ');
ALTER TABLE OPROS ALTER COLUMN ID_OPROSA SET DEFAULT nextval('OPROS_ID_OPROSA_SEQ');
ALTER TABLE VOPROS ALTER COLUMN ID_VOPROSA SET DEFAULT nextval('VOPROS_ID_VOPROSA_SEQ');
ALTER TABLE VARIANT_OTVETA ALTER COLUMN ID_VARIANTA SET DEFAULT nextval('VARIANT_OTVETA_ID_VARIANTA_SEQ');
ALTER TABLE RESPONDENT ALTER COLUMN ID_RESPONDENTA SET DEFAULT nextval('RESPONDENT_ID_RESPONDENTA_SEQ');
ALTER TABLE UCHASTIE ALTER COLUMN ID_UCHASTIYA SET DEFAULT nextval('UCHASTIE_ID_UCHASTIYA_SEQ');
ALTER TABLE OTVET ALTER COLUMN ID_OTVETA SET DEFAULT nextval('OTVET_ID_OTVETA_SEQ');

COMMENT ON SEQUENCE POL_ID_POLA_SEQ IS 'Sequence для генерации ID пола';
COMMENT ON SEQUENCE REGION_ID_REGIONA_SEQ IS 'Sequence для генерации ID региона';
COMMENT ON SEQUENCE UROVEN_OBRAZOVANIYA_ID_UROVNYA_SEQ IS 'Sequence для генерации ID уровня образования';
COMMENT ON SEQUENCE OPROS_ID_OPROSA_SEQ IS 'Sequence для генерации ID опроса';
COMMENT ON SEQUENCE VOPROS_ID_VOPROSA_SEQ IS 'Sequence для генерации ID вопроса';
COMMENT ON SEQUENCE VARIANT_OTVETA_ID_VARIANTA_SEQ IS 'Sequence для генерации ID варианта ответа';
COMMENT ON SEQUENCE RESPONDENT_ID_RESPONDENTA_SEQ IS 'Sequence для генерации ID респондента';
COMMENT ON SEQUENCE UCHASTIE_ID_UCHASTIYA_SEQ IS 'Sequence для генерации ID участия';
COMMENT ON SEQUENCE OTVET_ID_OTVETA_SEQ IS 'Sequence для генерации ID ответа';
